name: todo-bot
version: 0.1.0.0
github: 'githubuser/todo-bot'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2022 Author name here'

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/todo-bot#readme>

dependencies:
  - base >= 4.7 && < 5
  - calamity >= 0.3.0.0
  - optics >= 0.4.1 && < 0.5
  - lens >= 5.1 && < 6
  - di-polysemy ^>= 0.2
  - di >= 1.3 && < 2
  - df1 >= 0.3 && < 0.5
  - di-core ^>= 1.0.4
  - polysemy >= 1.5 && <2
  - polysemy-plugin >= 0.3 && <0.5
  - stm >= 2.5 && <3
  - text-show >= 3.8 && <4
  - text
  - data-default
  - data-flags
  - generic-lens

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fplugin=Polysemy.Plugin

library:
  source-dirs: src

executables:
  todo-bot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - todo-bot
    default-extensions:
      - DataKinds
      - OverloadedLabels
      - OverloadedStrings
      - TypeApplications

tests:
  todo-bot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - todo-bot
